- hosts: allhosts
  tasks:
  - name: Ansible check file exists example.
    stat:
      path: /var/tmp/abc
    register: file_details

  - debug:
      msg: "The file or directory exists"
    when: file_details.stat.exists
- hosts: allhosts
  tasks:
  - name: create file if not exist
  - file:
  path: /var/tmp/abc
  state: touch
  when: stat_result.stat.exists == False