---
- name: Download java and install
  hosts: allhosts
  get_url: "https://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jdk-8u202-linux-x64.tar.gz"
  dest: /tmp

- name: extract java
  shell: tar -zxvf /tmp/jdk-8u202-linux-x64.tar.gz