---
- hosts: allhosts
  tasks:
  - name: Download of java
    get_url:
      url: https://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jdk-8u202-linux-x64.tar.gz
      dest: /tmp
      headers: "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept.securebackup-cookie"
- name: install java
  unarchive:
    src: /tmp/jdk-8u202-linux-x64.tar.gz
    dest: /tmp
 